from __future__ import annotations

from pathlib import Path
import unittest

from patchharbor.compat_config import AliasSpec, CompatibilityConfig, LifecycleDefaults, WrapperSpec
from patchharbor.compat_planning import CompatibilityPlanAction, plan_compatibility
from patchharbor.compat_rendering import (
    CompatibilityRenderingError,
    RenderedWrapper,
    WrapperRenderOptions,
    render_action_preview,
    render_alias_block,
    render_alias_line,
    render_compatibility_preview,
    render_plan_preview,
    render_wrapper_script,
    render_wrappers,
    rendered_wrappers_to_mapping,
)


def sample_config() -> CompatibilityConfig:
    return CompatibilityConfig(
        source_name="example-project",
        wrappers=(
            WrapperSpec(
                name="patch-runner",
                kind="runner",
                relative_path="scripts/dev/run_patch.sh",
                command=("patchharbor", "run-script"),
                description="Run an explicit patch script",
            ),
            WrapperSpec(
                name="disabled-export",
                kind="export",
                relative_path="scripts/dev/export.sh",
                command=("patchharbor", "export"),
                enabled=False,
            ),
        ),
        aliases=(AliasSpec("run-patch", ("scripts/dev/run_patch.sh",), description="Run patch wrapper"),),
        lifecycle=LifecycleDefaults(downloads_dirname="downloads", done_dirname="done", failed_dirname="failed"),
    )


class PatchHarborCompatibilityRenderingTests(unittest.TestCase):
    def test_wrapper_render_options_validate_values(self) -> None:
        options = WrapperRenderOptions()
        self.assertEqual(options.shebang, "#!/usr/bin/env bash")
        self.assertTrue(options.strict_mode)
        self.assertTrue(options.pass_arguments)

        invalid = [
            lambda: WrapperRenderOptions(shebang="bash"),
            lambda: WrapperRenderOptions(shebang="#!/bin/bash\nbad"),
            lambda: WrapperRenderOptions(strict_mode="yes"),  # type: ignore[arg-type]
            lambda: WrapperRenderOptions(pass_arguments="yes"),  # type: ignore[arg-type]
            lambda: WrapperRenderOptions(generated_comment=""),
            lambda: WrapperRenderOptions(generated_comment="bad\ncomment"),
            lambda: WrapperRenderOptions(trailing_newline="yes"),  # type: ignore[arg-type]
        ]
        for factory in invalid:
            with self.subTest(factory=factory):
                with self.assertRaises(CompatibilityRenderingError):
                    factory()

    def test_render_wrapper_script_creates_shell_text_without_writing_file(self) -> None:
        wrapper = sample_config().wrapper_by_name("patch-runner")
        assert wrapper is not None
        rendered = render_wrapper_script(wrapper)

        self.assertEqual(rendered.relative_path, "scripts/dev/run_patch.sh")
        self.assertIn("#!/usr/bin/env bash", rendered.content)
        self.assertIn("Generated by PatchHarbor", rendered.content)
        self.assertIn("set -euo pipefail", rendered.content)
        self.assertIn('exec patchharbor run-script "$@"', rendered.content)
        self.assertTrue(rendered.content.endswith("\n"))
        self.assertGreater(rendered.line_count, 3)

    def test_render_wrapper_script_options_can_disable_strict_mode_args_and_trailing_newline(self) -> None:
        wrapper = sample_config().wrapper_by_name("patch-runner")
        assert wrapper is not None
        rendered = render_wrapper_script(
            wrapper,
            options=WrapperRenderOptions(strict_mode=False, pass_arguments=False, trailing_newline=False),
        )

        self.assertNotIn("set -euo pipefail", rendered.content)
        self.assertIn("exec patchharbor run-script", rendered.content)
        self.assertNotIn('"$@"', rendered.content)
        self.assertFalse(rendered.content.endswith("\n"))

    def test_render_wrappers_defaults_to_enabled_wrappers_only(self) -> None:
        rendered = render_wrappers(sample_config())
        self.assertEqual([wrapper.relative_path for wrapper in rendered], ["scripts/dev/run_patch.sh"])

        all_rendered = render_wrappers(sample_config(), include_disabled=True)
        self.assertEqual({wrapper.relative_path for wrapper in all_rendered}, {"scripts/dev/run_patch.sh", "scripts/dev/export.sh"})

    def test_render_alias_line_and_block(self) -> None:
        alias = sample_config().alias_by_name("run-patch")
        assert alias is not None
        line = render_alias_line(alias)
        self.assertEqual(line, "alias run-patch=scripts/dev/run_patch.sh")
        block = render_alias_block((alias,))
        self.assertEqual(block, line + "\n")
        self.assertEqual(render_alias_block(()), "")

    def test_render_alias_line_rejects_invalid_alias(self) -> None:
        with self.assertRaises(CompatibilityRenderingError):
            render_alias_line("bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_alias_line(AliasSpec("bad name", ("patchharbor",)))

    def test_render_plan_and_action_preview_use_existing_plan_contract(self) -> None:
        plan = plan_compatibility(sample_config(), existing_wrapper_paths=(), existing_aliases=())
        lines = render_plan_preview(plan)
        self.assertEqual(lines[0], "compatibility plan for example-project:")
        self.assertTrue(any("create_wrapper" in line for line in lines))

        action = CompatibilityPlanAction("create_alias", "run-patch", "alias is missing")
        self.assertEqual(render_action_preview(action), "create_alias: run-patch - alias is missing")

    def test_render_compatibility_preview_summarizes_config_and_plan(self) -> None:
        config = sample_config()
        plan = plan_compatibility(config)
        lines = render_compatibility_preview(config, plan)
        self.assertIn("compatibility preview for example-project", lines)
        self.assertIn("wrappers: 2", lines)
        self.assertIn("enabled wrappers: 1", lines)
        self.assertIn("aliases: 1", lines)
        self.assertIn("lifecycle: downloads/done/failed", lines)
        self.assertIn("planned actions: 4", lines)

    def test_rendered_wrapper_mapping_is_plain_data(self) -> None:
        wrapper = sample_config().wrapper_by_name("patch-runner")
        assert wrapper is not None
        rendered = render_wrapper_script(wrapper)
        mapping = rendered.to_mapping()
        self.assertEqual(mapping["relative_path"], "scripts/dev/run_patch.sh")
        self.assertIn("content", mapping)
        self.assertIn("line_count", mapping)
        self.assertEqual(rendered_wrappers_to_mapping((rendered,))[0]["relative_path"], "scripts/dev/run_patch.sh")

    def test_rendering_validates_wrong_types(self) -> None:
        with self.assertRaises(CompatibilityRenderingError):
            render_wrapper_script("bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_wrappers("bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_wrappers(sample_config(), include_disabled="yes")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_plan_preview("bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_action_preview("bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_compatibility_preview("bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            render_compatibility_preview(sample_config(), plan="bad")  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            rendered_wrappers_to_mapping(("bad",))  # type: ignore[arg-type]
        with self.assertRaises(CompatibilityRenderingError):
            RenderedWrapper("/absolute.sh", "content")

    def test_rendering_does_not_write_files(self) -> None:
        root = Path(__file__).resolve().parents[1]
        target = root / "scripts/dev/run_patch.sh"
        self.assertFalse(target.exists())
        render_wrappers(sample_config())
        self.assertFalse(target.exists())

    def test_compat_rendering_files_do_not_store_local_private_values(self) -> None:
        root = Path(__file__).resolve().parents[1]
        checked = [
            root / "src/patchharbor/compat_rendering.py",
            root / "tests/test_compat_rendering.py",
        ]
        text = "\n".join(path.read_text(encoding="utf-8") for path in checked)
        forbidden = [
            "/home/" + "exampleuser",
            "user" + "@",
            "example.user" + "@" + "example.invalid",
            "Example" + "Laptop",
            "~/" + "Projects",
            "run_latest_" + "download_patch",
            chr(96) * 3,
        ]
        for value in forbidden:
            with self.subTest(value=value):
                self.assertNotIn(value, text)
