from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath
import re
import shlex
from typing import Iterable, Mapping

from patchharbor.compat_config import AliasSpec, CompatibilityConfig, WrapperSpec
from patchharbor.compat_planning import CompatibilityPlan, CompatibilityPlanAction


class CompatibilityRenderingError(ValueError):
    pass


@dataclass(frozen=True)
class WrapperRenderOptions:
    shebang: str = "#!/usr/bin/env bash"
    strict_mode: bool = True
    pass_arguments: bool = True
    generated_comment: str = "Generated by PatchHarbor compatibility rendering."
    trailing_newline: bool = True

    def __post_init__(self) -> None:
        _require_non_empty_string(self.shebang, "shebang")
        if "\n" in self.shebang or "\r" in self.shebang:
            raise CompatibilityRenderingError("shebang must be a single line")
        if not self.shebang.startswith("#!"):
            raise CompatibilityRenderingError("shebang must start with #!")
        if not isinstance(self.strict_mode, bool):
            raise CompatibilityRenderingError("strict_mode must be a boolean")
        if not isinstance(self.pass_arguments, bool):
            raise CompatibilityRenderingError("pass_arguments must be a boolean")
        _require_non_empty_string(self.generated_comment, "generated_comment")
        if "\n" in self.generated_comment or "\r" in self.generated_comment:
            raise CompatibilityRenderingError("generated_comment must be a single line")
        if not isinstance(self.trailing_newline, bool):
            raise CompatibilityRenderingError("trailing_newline must be a boolean")


@dataclass(frozen=True)
class RenderedWrapper:
    relative_path: str
    content: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "relative_path", _relative_path_string(self.relative_path, "relative_path"))
        _require_non_empty_string(self.content, "content")

    @property
    def line_count(self) -> int:
        return len(self.content.splitlines())

    def to_mapping(self) -> dict[str, object]:
        return {
            "relative_path": self.relative_path,
            "content": self.content,
            "line_count": self.line_count,
        }


def render_wrapper_script(wrapper: WrapperSpec, *, options: WrapperRenderOptions | None = None) -> RenderedWrapper:
    if not isinstance(wrapper, WrapperSpec):
        raise CompatibilityRenderingError("wrapper must be a WrapperSpec")
    effective_options = options or WrapperRenderOptions()

    lines = [
        effective_options.shebang,
        f"# {effective_options.generated_comment}",
    ]
    if wrapper.description:
        lines.append(f"# {wrapper.description}")
    if effective_options.strict_mode:
        lines.append("set -euo pipefail")
    lines.append("")
    command = shlex.join(wrapper.command)
    if effective_options.pass_arguments:
        command = f'{command} "$@"'
    lines.append(f"exec {command}")

    content = "\n".join(lines)
    if effective_options.trailing_newline:
        content += "\n"
    return RenderedWrapper(wrapper.relative_path, content)


def render_wrappers(config: CompatibilityConfig, *, options: WrapperRenderOptions | None = None, include_disabled: bool = False) -> tuple[RenderedWrapper, ...]:
    if not isinstance(config, CompatibilityConfig):
        raise CompatibilityRenderingError("config must be a CompatibilityConfig")
    if not isinstance(include_disabled, bool):
        raise CompatibilityRenderingError("include_disabled must be a boolean")
    wrappers = config.wrappers if include_disabled else config.enabled_wrappers()
    return tuple(render_wrapper_script(wrapper, options=options) for wrapper in wrappers)


def render_alias_line(alias: AliasSpec) -> str:
    if not isinstance(alias, AliasSpec):
        raise CompatibilityRenderingError("alias must be an AliasSpec")
    _validate_alias_name(alias.name)
    return f"alias {alias.name}={shlex.quote(alias.render_command())}"


def render_alias_block(aliases: Iterable[AliasSpec]) -> str:
    alias_tuple = _alias_tuple(aliases)
    lines = [render_alias_line(alias) for alias in alias_tuple]
    return "\n".join(lines) + ("\n" if lines else "")


def render_plan_preview(plan: CompatibilityPlan) -> tuple[str, ...]:
    if not isinstance(plan, CompatibilityPlan):
        raise CompatibilityRenderingError("plan must be a CompatibilityPlan")
    return plan.render_lines()


def render_action_preview(action: CompatibilityPlanAction) -> str:
    if not isinstance(action, CompatibilityPlanAction):
        raise CompatibilityRenderingError("action must be a CompatibilityPlanAction")
    return action.render()


def render_compatibility_preview(config: CompatibilityConfig, plan: CompatibilityPlan | None = None) -> tuple[str, ...]:
    if not isinstance(config, CompatibilityConfig):
        raise CompatibilityRenderingError("config must be a CompatibilityConfig")
    if plan is not None and not isinstance(plan, CompatibilityPlan):
        raise CompatibilityRenderingError("plan must be a CompatibilityPlan when provided")

    lines = [
        f"compatibility preview for {config.source_name}",
        f"wrappers: {len(config.wrappers)}",
        f"enabled wrappers: {len(config.enabled_wrappers())}",
        f"aliases: {len(config.aliases)}",
        f"lifecycle: {config.lifecycle.downloads_dirname}/{config.lifecycle.done_dirname}/{config.lifecycle.failed_dirname}",
    ]
    if plan is not None:
        lines.append(f"planned actions: {len(plan.actions)}")
    return tuple(lines)


def rendered_wrappers_to_mapping(wrappers: Iterable[RenderedWrapper]) -> tuple[Mapping[str, object], ...]:
    wrapper_tuple = _rendered_wrapper_tuple(wrappers)
    return tuple(wrapper.to_mapping() for wrapper in wrapper_tuple)


def _alias_tuple(values: Iterable[AliasSpec]) -> tuple[AliasSpec, ...]:
    if isinstance(values, (str, bytes)):
        raise CompatibilityRenderingError("aliases must be an iterable of AliasSpec, not a string")
    try:
        aliases = tuple(values)
    except TypeError as exc:
        raise CompatibilityRenderingError("aliases must be an iterable of AliasSpec") from exc
    for alias in aliases:
        if not isinstance(alias, AliasSpec):
            raise CompatibilityRenderingError("aliases must contain AliasSpec items")
    return aliases


def _rendered_wrapper_tuple(values: Iterable[RenderedWrapper]) -> tuple[RenderedWrapper, ...]:
    if isinstance(values, (str, bytes)):
        raise CompatibilityRenderingError("rendered wrappers must be an iterable, not a string")
    try:
        wrappers = tuple(values)
    except TypeError as exc:
        raise CompatibilityRenderingError("rendered wrappers must be an iterable") from exc
    for wrapper in wrappers:
        if not isinstance(wrapper, RenderedWrapper):
            raise CompatibilityRenderingError("rendered wrappers must contain RenderedWrapper items")
    return wrappers


def _relative_path_string(value: object, field: str) -> str:
    _require_non_empty_string(value, field)
    assert isinstance(value, str)
    path = PurePosixPath(value)
    if path.is_absolute():
        raise CompatibilityRenderingError(f"{field} must be repository-relative")
    if any(part in ("", ".", "..") for part in path.parts):
        raise CompatibilityRenderingError(f"{field} must not contain empty, current, or parent path parts")
    if ".git" in path.parts:
        raise CompatibilityRenderingError(f"{field} must not point inside .git")
    return str(path)


_ALIAS_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def _validate_alias_name(value: str) -> None:
    _require_non_empty_string(value, "alias name")
    if not _ALIAS_NAME_RE.fullmatch(value):
        raise CompatibilityRenderingError("alias name contains unsupported shell characters")


def _require_non_empty_string(value: object, field: str) -> None:
    if not isinstance(value, str) or not value:
        raise CompatibilityRenderingError(f"{field} must be a non-empty string")
